title: Kunru Zou
description: Assistant Professor, Department of Accountancy, Economics and Finance, Hong Kong Baptist University
theme: minima
markdown: kramdown
header_pages:
  - index.md
  - research.md
  - teaching.md
  - cv.md
